//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Service.WebServicesTests.ProjetoWSServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PMResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PMResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        private bool SucessoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Sucesso {
            get {
                return this.SucessoField;
            }
            set {
                if ((this.SucessoField.Equals(value) != true)) {
                    this.SucessoField = value;
                    this.RaisePropertyChanged("Sucesso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProjetoWSServiceReference.ProjetoWSSoap")]
    public interface ProjetoWSSoap {
        
        // CODEGEN: Generating message contract since element name AdicionarMembroProjetoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdicionarMembroProjeto", ReplyAction="*")]
        PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoResponse AdicionarMembroProjeto(PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdicionarMembroProjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoResponse> AdicionarMembroProjetoAsync(PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdicionarMembroProjetoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdicionarMembroProjeto", Namespace="http://tempuri.org/", Order=0)]
        public PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoRequestBody Body;
        
        public AdicionarMembroProjetoRequest() {
        }
        
        public AdicionarMembroProjetoRequest(PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdicionarMembroProjetoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long idProjeto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long idMembro;
        
        public AdicionarMembroProjetoRequestBody() {
        }
        
        public AdicionarMembroProjetoRequestBody(long idProjeto, long idMembro) {
            this.idProjeto = idProjeto;
            this.idMembro = idMembro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdicionarMembroProjetoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdicionarMembroProjetoResponse", Namespace="http://tempuri.org/", Order=0)]
        public PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoResponseBody Body;
        
        public AdicionarMembroProjetoResponse() {
        }
        
        public AdicionarMembroProjetoResponse(PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdicionarMembroProjetoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PM.Service.WebServicesTests.ProjetoWSServiceReference.PMResponse AdicionarMembroProjetoResult;
        
        public AdicionarMembroProjetoResponseBody() {
        }
        
        public AdicionarMembroProjetoResponseBody(PM.Service.WebServicesTests.ProjetoWSServiceReference.PMResponse AdicionarMembroProjetoResult) {
            this.AdicionarMembroProjetoResult = AdicionarMembroProjetoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProjetoWSSoapChannel : PM.Service.WebServicesTests.ProjetoWSServiceReference.ProjetoWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjetoWSSoapClient : System.ServiceModel.ClientBase<PM.Service.WebServicesTests.ProjetoWSServiceReference.ProjetoWSSoap>, PM.Service.WebServicesTests.ProjetoWSServiceReference.ProjetoWSSoap {
        
        public ProjetoWSSoapClient() {
        }
        
        public ProjetoWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjetoWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjetoWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjetoWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoResponse PM.Service.WebServicesTests.ProjetoWSServiceReference.ProjetoWSSoap.AdicionarMembroProjeto(PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoRequest request) {
            return base.Channel.AdicionarMembroProjeto(request);
        }
        
        public PM.Service.WebServicesTests.ProjetoWSServiceReference.PMResponse AdicionarMembroProjeto(long idProjeto, long idMembro) {
            PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoRequest inValue = new PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoRequest();
            inValue.Body = new PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoRequestBody();
            inValue.Body.idProjeto = idProjeto;
            inValue.Body.idMembro = idMembro;
            PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoResponse retVal = ((PM.Service.WebServicesTests.ProjetoWSServiceReference.ProjetoWSSoap)(this)).AdicionarMembroProjeto(inValue);
            return retVal.Body.AdicionarMembroProjetoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoResponse> PM.Service.WebServicesTests.ProjetoWSServiceReference.ProjetoWSSoap.AdicionarMembroProjetoAsync(PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoRequest request) {
            return base.Channel.AdicionarMembroProjetoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoResponse> AdicionarMembroProjetoAsync(long idProjeto, long idMembro) {
            PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoRequest inValue = new PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoRequest();
            inValue.Body = new PM.Service.WebServicesTests.ProjetoWSServiceReference.AdicionarMembroProjetoRequestBody();
            inValue.Body.idProjeto = idProjeto;
            inValue.Body.idMembro = idMembro;
            return ((PM.Service.WebServicesTests.ProjetoWSServiceReference.ProjetoWSSoap)(this)).AdicionarMembroProjetoAsync(inValue);
        }
    }
}
